language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: 
    - python test/linked_list_tests.py
    - python test/stack_tests.py
    - python test/queue_tests.py
    - python test/hash_tests.py
    - python test/make_month_tests.py